version: '3.9'
services:
  php:
    build: ./php
    volumes:
      - ./app:/var/www/html
    ports:
      - "3000:80"
    depends_on:
      - mysql

  mysql:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password